### ISSUE TITLE
Change name of primary key field that is automatically generated

### ISSUE THREAD

**Issue by filipeteles** [ContinuumIO/datashape#138]
Is it possible to change it from the default 'id', to something else?

**Comment by mrocklin** [comment]
In what context is datashape generating a primary key?  Is it possible that this is happening within your database?

**Comment by cpcloud** [comment]
To be clear, datashape knows nothing about primary keys so we don't generate any default names.

**Comment by cpcloud** [comment]
closing as not a bug
