### ISSUE TITLE
Add documentation about typevar vs type upper/lowercase convention

### ISSUE THREAD

**Issue by mwiebe** [ContinuumIO/datashape#20]
Need documentation about this.

**Comment by cpcloud** [comment]
@mwiebe can you give an example of what needs to be clarified?

**Comment by mwiebe** [comment]
The way it works is that names beginning with an uppercase characters are symbolic, and names beginning with a lowercase character are concrete. So Fixed is the symbolic version of of the dimension type fixed[10]. If you read in the documentation e.g. at http://datashape.pydata.org/overview.html, you see no mention of this convention.

If you read the grammar doc http://datashape.pydata.org/grammar.html, there is some mention of this, that typevars always start with a capital letter. The generalization of that to have any symbolic type begin with a capital is something we've done in DyND.

 I guess this leads to the question of how we should be keeping DyND's types and ContinuumIO/datashape types in sync? For example, we've added syntax so 'Fixed ** 3 * int32' means a 3-dimensional array, and 'Fixed ** N * int32' means a more general N-dimensional array, where the N is named so is available for matching/substitution. Do you have someone to update the implementation/docs here so things line up?

**Comment by cpcloud** [comment]
My immediate concern was whether addressing this issue was achievable in a week's time. I'm going to push this to the next release. I'll comment on your comments in a bit.
