### ISSUE TITLE
Datashape functions should accept strings

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/datashape#41]
```Python
In [5]: datashape.to_numpy('3 * 3 * int32')
NotNumpyCompatible: DataShape measure 3 * 3 * int32 is not NumPy-compatible

In [6]: datashape.to_numpy(datashape.dshape('3 * 3 * int32'))
Out[6]: ((3, 3), dtype('int32'))
```

**Comment by denniskl** [comment]
Hi Matthew, I'm currently trying to convert a csv file to the hdf5 format using into. Now, I'm falling into this issue "DataShape measure ?string is not NumPy-compatible". Would be great if you can have a look at implementing strings in datashape (if it is relatively easy to implement)...

**Comment by mrocklin** [comment]
This issue was originally about the datashape manipulation functions and whether or not they should accept Python strings rather than DataShape objects as inputs.  This is mostly syntactic sugar.

Your issue seems different.  You're asking about how we choose to interpret option types / missing values in numpy (the dshape `?foo` implies `foo's with missing values`).  We actually already do this for numpy.

```Python
In [1]: from into import *

In [2]: into(np.ndarray, 'foo.csv')
Out[2]: 
rec.array([(u'Alice', 100.0), (u'Bob', 200.0)], 
      dtype=[('name', 'O'), ('balance', '<f8')])

In [3]: discover(resource('foo.csv'))
Out[3]: dshape("var * {name: ?string, balance: ?int64}")
```

In https://github.com/ContinuumIO/into/commit/a42df4b625f2312b89aa4f0ace5fa8c8c960bb9f I've hooked up this same logic to `h5py` which I hope should solve your problem.

**Comment by cpcloud** [comment]
@mrocklin How strong do you feel about this working? An extra single function call doesn't seem that bad to me.

**Comment by mrocklin** [comment]
Not strongly.

**Comment by cpcloud** [comment]
closing as a `wontfix`
