### ISSUE TITLE
Use list of lists to construct Records in dshape

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/datashape#48]
We should support construction of all datashapes through python syntax and data structures.  This allows for simpler programmatic construction than string manipulation.

One case where this is difficult is records, e.g.

    '{name: string, amount: int}'

In datashape the order matters while in Python the order doesn't

    {'name': string, 'amount': int} == {'amount': int, 'name': string}

The standard fallback is to use a sequence of items

    [['name', string], ['amount', 'int']]

Maybe the utility function `dshape` should recognize this situation and produce the appropriate `Record`

**Comment by cpcloud** [comment]
closing in favor of #71
