### ISSUE TITLE
weird corner cases in discover

### ISSUE THREAD

**Issue by mwiebe** [ContinuumIO/datashape#88]
```
In [28]: discover(['', 1, 2])
Out[28]: dshape("(null, int64, int64)")

In [29]: discover(['ab', 1, 2])
Out[29]: dshape("(string, int64, int64)")
```

**Comment by cpcloud** [comment]
@mwiebe Are you expecting these to do the same thing?

**Comment by mwiebe** [comment]
Yes, this was surprising behaviour to me because '' seems unambiguously a string to me, as that's it's Python type. Treating '' as null makes sense for something like a csv loading auto-detection, but not in general. Even in csv, I think this approach doesn't quite capture the possible subtleties, e.g.:

```
Name, Value
"First", 1
"", 2
"Blah, 5
```

compared to

```
Name, Value
"First", 1
, 2
"Blah, 5
```

I would say in the first example Name would be type "string", and in the second example Name would be type "?string". Maybe this is nitpicking, though, and most other systems aren't consistent enough to make it worth doing this. But I seem to recall the CSV output of R does distinguish between an unquoted NA and a quoted "NA" as a missing value vs a string that might mean North America.

**Comment by cpcloud** [comment]
pushing to 0.4.6

**Comment by cpcloud** [comment]
I think this behaves in a sane way:

```
In [1]: cat foo.csv
a,b,c
,"",1.0
1,"CAN",2.0

In [2]: with open('foo.csv', 'rU') as f:
   ...:     data = [line.strip().split(',') for line in f]
   ...:

In [3]: a, b, c = zip(*data[1:])  # skip the header

In [4]: discover(a)
Out[4]: dshape("(null, int64)")

In [5]: discover(b)
Out[5]: dshape("2 * string")

In [6]: discover(c)
Out[6]: dshape("2 * float64")

In [7]: from odo import CSV

In [8]: discover(CSV('foo.csv'))
Out[8]: dshape("var * {a: ?float64, b: ?string, c: ?float64}")
```
