### ISSUE TITLE
Need tests to verify whether ds == eval(str(ds)) for all datashapes

### ISSUE THREAD

**Issue by talumbau** [ContinuumIO/datashape#90]
A recent PR (https://github.com/ContinuumIO/datashape/pull/89) came about because one could make a datashape where eval(str(ds)) != ds. It would be helpful if we exhaustively tested this within datashape.

**Comment by cpcloud** [comment]
i think truly exhaustive testing of this is not practically doable. However a subset of dshapes that tries to characterize the scope of possible dshapes is definitely doable. Putting up a PR in a few
