### ISSUE TITLE
Incorrect datetime discovery

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/datashape#91]
```Python
In [5]: discover("31-DEC-99 12.00.00.000000000 AM")
Out[5]: Date()
```

Should be datetime

**Comment by cpcloud** [comment]
This is now returning `string`

```python
In [14]: discover("31-DEC-99 12.00.00.000000000")
Out[14]: ctype("string")
```

**Comment by cpcloud** [comment]
I don't think `.` is a valid time separator.

**Comment by mrocklin** [comment]
Personally I'm fine if our datetime detection doesn't work on every possible format.

**Comment by cpcloud** [comment]
Okay. I'll add a test for this and close the issue in the PR
